#!/usr/bin/expect -f
set timeout 180
spawn ssh -o StrictHostKeyChecking=no user@192.168.31.14
expect "assword:"
send "12345\r"
expect "$ "
send "sudo -i\r"
expect "Password:"
send "12345\r"
expect "# "
send "curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && chmod +x get_helm.sh && ./get_helm.sh\r"
expect "# "
send "mv /usr/local/bin/helm /usr/bin/helm\r"
expect "# "
send "helm repo add prometheus-community https://prometheus-community.github.io/helm-charts\r"
expect "# "
send "helm repo update\r"
expect "# "
send "kubectl create namespace prometheus\r"
expect "# "
send "helm install prometheus prometheus-community/kube-prometheus-stack -n prometheus --set grafana.enabled=false --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false\r"
expect "# "
send "exit\r"
expect eof
