#!/usr/bin/expect -f
set timeout 15
spawn ssh -o StrictHostKeyChecking=no user@192.168.31.14
expect "assword:"
send "12345\r"
expect "$ "
send "curl -s \"http://10.43.232.169:9090/api/v1/query?query=kubevirt_vmi_storage_read_traffic_bytes_total\" | python3 -c \"import sys, json; data = json.load(sys.stdin); print(json.dumps(data['data']['result'][:2], indent=2))\" \r"
expect "$ "
send "exit\r"
expect eof
