#!/usr/bin/expect -f
set timeout 15
spawn ssh -o StrictHostKeyChecking=no user@192.168.31.14
expect "assword:"
send "12345\r"
expect "$ "
send "sudo -S rm -rf /etc/cni/net.d\r"
expect "assword:"
send "12345\r"
expect "$ "
send "sudo -S ln -s /var/lib/rancher/k3s/agent/etc/cni/net.d /etc/cni/net.d\r"
expect "$ "
send "sudo -S kubectl -n kube-system rollout restart ds/kube-multus-ds\r"
expect "$ "
send "exit\r"
expect eof
